### ISSUE TITLE
Plugin causes other phases to trigger all exec:exec tasks

### ISSUE THREAD

**Issue by shepdl** [allegro/grunt-maven-plugin#71]
I have a project with a POM that uses the exec plugin to run a demo server. Once I add grunt-maven-plugin to my POM, most tasks cause the exec plugin task in my POM to get called.

Here's a minimal POM that reproduces the problem: https://gist.github.com/shepdl/1743e8977e9de52fb6c4. You shouldn't get an error about the missing com.foo.ExecProbDemo class unless you run exec:exec, but it will give you an error when you run `grunt:npm`, `grunt:bower`, and `grunt:grunt`, and even `mvn package` (though `grunt:create-resources` works fine). If you remove grunt-maven-plugin, though, the exec task won't be triggered.

**Comment by adamdubiel** [comment]
Thanks for code sample, i will get back to you when i debug this case.

**Comment by adamdubiel** [comment]
I got to the bottom of the issue: internally i call *maven-exec* to invoke external commands (*npm*, *bower* etc). I simply call the *exec* target, without specifying execution id.

If you changed your example and erroneous execution had ID assigned:

```
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <version>1.2.1</version>
        <executions>
            <execution>
                <id>myExecution</id>
                <configuration>
                    <executable>java</executable>
                    <arguments>
                        <argument>com.foo.ExecProbDemo</argument>
                     </arguments>
                 </configuration>
             </execution>
         </executions>
</plugin>
``` 

It would not be called. Quick review of [MojoExecutor](https://github.com/TimMoore/mojo-executor) plugin i use internally shows no way to assign custom id to executions inside GMP.. so i can't fence it.

**Comment by shepdl** [comment]
Ok, thanks! I'll make that change.
