### ISSUE TITLE
Configuration per environment

### ISSUE THREAD

**Issue by chemoish** [allegro/grunt-maven-plugin#78]
Is it possible to configure this plugin to run specific tasks per environment?

`grunt build:development` vs `grunt build:production`

Is it possible to configure this plugin to automate the grunt tasks for each environment that I would have to manually execute otherwise (i.e. I don't need it to watch, create a target-grunt dir, manage anything more than have maven execute the commands I would manually run)?

**Comment by adamdubiel** [comment]
Yes - you can pass which grunt target to run:

```
<configuration>
    <target>myTarget</target>
</configuration>
```

Or you can also set this variable from command line:

```
$ mvn package -Dgrunt.target=myTarget
```

**Comment by chemoish** [comment]
I know very little about the java/mvn/tomcat stack, but I am a FE developer. I found http://stackoverflow.com/questions/4660047/override-maven-plugin-configuration-defined-in-the-pom-pluginmanagement-from-the. It mentions that you cannot execute what you mentioned above unless you define a variable.

pom.xml
```xml
<properties>
  <grunt.target>build:production</grunt.target>
</properties>

...

<configuration>
   <target>${grunt.target}</target>
</configuration>
```

Overriding pom.xml from the command line:
```sh
grunt:grunt -Dgrunt.target=build:development
````

IDE will add command line to execute during run and build servers will automatically inherit the default target.

I'll think it is best to separately run all grunt/watch tasks from the command line. But at least this way maven can execute the build tasks you want when it compiles.

**Comment by adamdubiel** [comment]
Of course you are right, i wrote the solution too quickly without checking it, and my memory failed me this time. Hope that this solves the problem anyway :)
