### ISSUE TITLE
Copying JS files from dist to target

### ISSUE THREAD

**Issue by madders** [allegro/grunt-maven-plugin#82]
I'm trying to join together a Maven and Grunt project to build into a single war. Unfortunately I don't have much experience with either Maven or Grunt.

Our existing Gruntfile.js uses sass and uglify and outputs everything to the destination directory ```dist``` (in ```target-grunt```). So it doesn't make sense to me that GMP is also copying the original files to ```dist```. I'm sure I must be missing something obvious.

As per the instructions here, I updated the default Grunt task so it starts with mavenPrepare and ends with mavenDist. So if the tasks inbetween are processing the JavaScript files producing new ones, the mavenDist task should only take those new ones right? Currently it's copying everything, including ```node_modules``` into the ```dist``` folder. It's then also copying everything, including ```node_modules``` again into the ```target``` folder. And then everything is copied again to the ```target/warname``` folder. Is this the correct behaviour?

**Comment by adamdubiel** [comment]
It all depends on your configuration. This is just me guessing, as i don't know how you configured your stuff, but there is setting called [deliverables](https://github.com/allegro/grunt-maven-npm#optionsdeliverables]) in Grunt ,that allows you to choose what to copy. Just leave an empty array there and nothing will be copied from `target-grunt` to `target-grunt/dist`:

```
mavenDist: {
    options: {
      deliverables: [],
    }
}
```

**Comment by madders** [comment]
Ok thank you - that works. The documentation makes it sound like the deliverables are copied from ```target-grunt``` to both ```target-grunt/dist``` and ```target/warname```, but it looks like they are actually copied from ```target-grunt``` to ```target-grunt/dist``` then everything from there to ```target/warname```. 

I have one other question. What is the difference between the create-resources goal and mavenPrepare grunt task? Aren't they doing the same thing? So when I run maven are the contents of the jsSourceDirectory getting copied twice?

**Comment by adamdubiel** [comment]
`mavenPrepare` task is here for more continuous build capabilities, you change something in your IDE and it's available in your webapp. Basically yes, it mimics `processResources`, it does not have to be included in default grunt target ,rather some kind of `develop` target, which uses `grunt watch` etc..
