### ISSUE TITLE
Add a copy only option

### ISSUE THREAD

**Issue by sDaniel** [allegro/grunt-maven-plugin#87]
As far as I understand there currently is only an option to disable the plugin run all together: 

    <configuration>
        <disabled>${skipGrunt}</disabled> 
    </configuration>

Is there an option to skip the frontend rebuild and only copy the previously built frontend dist (to save time during backend development)?

**Comment by adamdubiel** [comment]
Hmm.. since plugin is only calling grunt, it depends on grunt target that you will call - you could call some no-op job depending on current profile/variable, like:

```
<configuration>
    <target>${target}</target>
</configuration>
```

**Comment by sDaniel** [comment]
OK good idea thanks for the fast feedback!
