### ISSUE TITLE
How to create tar-ed npm modules

### ISSUE THREAD

**Issue by sohansoni** [allegro/grunt-maven-plugin#90]
I am using grunt-maven-plugin for building my Java + Angular JS application, and I don't want to download node modules every time I build this.

As per note on grunt-maven-plugin, it says use tar-ed node_modules instead of running npm install during each build.

Now how to create **tar-ed node_modules** ? I am guessing, its somekind of zipping the directory but not exactly sure. Is it possible through tools like winzip, 7zip ? Or Do I need to use one more node module to achieve this ?

**Comment by adamdubiel** [comment]
It's all in [this paragraph](https://github.com/allegro/grunt-maven-plugin#preparing-node_modulestar) in readme. It uses Unix `tar` to create single archive containing all files.

**Comment by sohansoni** [comment]
I see, I use windows and hence missed that part. 
On windows I achieved this using 7zip.  

Again thanks for responding so quick, I am closing this issue.
